### ISSUE TITLE
File Identifier

### ISSUE THREAD

**Issue by mrkaroshi** [urbste/ImprovedOcamCalib#2]
Running your code on Matlab 2015 OSX, I'm getting this error:

`
Error using fclose
Invalid file identifier. Use fopen to generate a valid file identifier.

Error in get_checkerboard_cornersUrban (line 94)
    fclose(fid);

Error in click_calibUrban (line 269)
        [callBack, x, y]  = get_checkerboard_cornersUrban(kk,use_corner_find,calib_data);

Error while evaluating UIControl Callback
`

Straight after I run 'Extract grid corners', have you encountered this before? I've checked my path to make sure it includes all of the files, I've got adequate permissions to run and access everything, have I missed something?

**Comment by mrkaroshi** [comment]
This page seems to shed some light on this: [https://groups.google.com/forum/#!topic/ocamcalib-toolbox/P1VUxE66uD8](url)

But I'm honestly not sure how to orchestrate the solution they suggest, is that meant to be integrated into the code or input into the Command Window? The Command Window doesn't seem to do anything.

**Comment by urbste** [comment]
Hey,

I guess this is a problem related to the FindCorners function of the original toolbox.
This is an external C++ function that you need to compile for your system.
Since I'm on Windows I can't really tell you how to build it on OSX but I think there is a download provided on the homepage of the author.

If you have an executable version of that function one solution posted in the Q&A might be to execute  setenv('LD_LIBRARY_PATH', '');
in your Matlab command window. This adds the necessary libraries (opencv dynamic libs) to the search path.

Cheers
Steffen

**Comment by mrkaroshi** [comment]
Thanks for your help Steffen, ended up just virtualising and using the Windoze version of Matlab. Cheers anyway!
